### ISSUE TITLE
Sort "Installed" top most

### ISSUE THREAD

**Issue by sandriaas** [prezesp/scoop-viewer#30]
would be great if the "installed" packages can be sorted as top most.

**Comment by prezesp** [comment]
I agree this is a pretty cool feature. It will be included in the newest version of scoop-viewer.

**Comment by prezesp** [comment]
A new version is available. With this version, I decided to start using the `semantic versioning`, so you need to uninstall scoop-viewer first because scoop doesn't know which version is newer.
